name: Report code coverage

on:
  push:
    branches: 
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: generate code coverage report
      run: ./gradlew clean test jacocoTestReport
    - uses: codecov/codecov-action@v1
      name: upload report
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/report.xml
        name: codecov-umbrella
        fail_ci_if_error: true
