name: Docker Image CI

on:
  push:
    branches: 
    - master

jobs: 

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag laterality/greeter:latest

    - name: Push docker image
      run: |
        docker login -u ${{ secrets.docker_username }} --password ${{ secrets.docker_password }}
        docker push laterality/greeter:latest

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/report.xml
        name: codecov-umbrella
        fail_ci_if_error: true

